spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.20.11:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driverClassName: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-order
  rabbitmq:
    host: 192.168.20.11
    port: 5672
    virtual-host: /
    publisher-returns: true
    publisher-confirms: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: 192.168.20.11
    port: 6379
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 9000